version: 1
services:
  web:
    type: web
    name: shiquoapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn shiquoweb.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      DATABASE_URL: "mysql://shiquo:shiquo254@localhost/shiquo"  # Updated with actual database credentials
    staticPublishPath: static/
